#!/bin/sh

set -eu

usage() {
    echo 'usage: awesome-launch [options] COMMAND...

options:
  -h          Show help message
  -s          Launch with systemd-run
  -j          Launch with firejail
  -f FACTORY  Launch via a window factory
  -i ID       The single instance ID to use
  -1          Spawn if not already running
  -r          Raise or spawn'
}

usage_error() {
    usage >&2
    exit 2
}

while getopts ':hsjf:i:1r' opt; do
    case "$opt" in
        h) usage; exit ;;
        s) systemd=true ;;
        j) firejail=true ;;
        f) factory="$OPTARG" ;;
        i) id="$OPTARG" ;;
        1) func='spawn.single_instance' ;;
        r) func='spawn.raise_or_spawn' ;;
        *) usage_error
    esac
done

shift $((OPTIND - 1))

[ $# -eq 0 ] && usage_error

awesome-client "
args = {
    ${id+id = '$id',}
    ${systemd+systemd = '$systemd',}
    ${firejail+firejail = '$firejail',}
    ${factory+factory = '$factory',}
}
require('awesome-launch').${func-spawn}('$*', args)
"
