#!/bin/sh

set -eu

usage() {
    echo 'usage: awesome-launch [options] COMMAND...

options:
  -h          Show help message
  -j          Launch with firejail
  -f FACTORY  Launch via a window factory
  -i ID       The single instance ID to use
  -s          Spawn if not already running
  -r          Raise or spawn'
}

usage_error() {
    usage >&2
    exit 2
}

while getopts ':hjf:i:sr' opt; do
    case "$opt" in
        h) usage; exit ;;
        j) firejail=true ;;
        f) factory="$OPTARG" ;;
        i) id="$OPTARG" ;;
        s) func='s' ;;
        r) func='r' ;;
        *) usage_error
    esac
done

shift $((OPTIND - 1))

[ $# -eq 0 ] && usage_error

case "${func-}" in
    s) name='spawn.single_instance' ;;
    r) name='spawn.raise_or_spawn' ;;
    *) name='spawn'
esac

awesome-client "
args = {
    ${id+id = '$id',}
    ${firejail+firejail = '$firejail',}
    ${factory+factory = '$factory',}
}
require('awesome-launch').$name('$*', args)
"
